networks:
  net: { name: local, driver: bridge, external: true }

services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    extra_hosts:
      host.docker.internal: host-gateway
    #network_mode: host
    networks:
      net:
        aliases: ["caddy.svc"]
    ports: [80:80]
    volumes:
    - ./configs/localhost.caddy:/etc/caddy/Caddyfile:ro

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    expose: ["80"]
    #networks: [net]
    networks:
      net:
        aliases: ["whoami.svc"]
    #ports: ["8001:80"]

  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: always
    networks:
      net:
        aliases: ["excalidraw.svc"]
    #ports: ["5000:80"]
