# path: /etc/dnsmasq.d/dnsmasq.localhost.conf
# command: dnsmasq --test
# command: systemctl restart dnsmasq

no-resolv
server=1.1.1.1
server=8.8.8.8

#host-record=whoami.localhost,127.0.0.1:8001
address=/localhost/127.0.0.1
