FROM python:3.14-trixie

#### 1. passing args
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

ARG user_uid=1000
ARG user_gid=1000

# DEBIAN_FRONTEND=noninteractive

#### 2. installation
COPY ./copy_files/scripts /opt/scripts

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

RUN bash /opt/scripts/install_nodejs.sh && \
    /opt/scripts/apt_install.sh tzdata locales ca-certificates gnupg \
      python3 python3-venv python3-pip python3-dev \
      zip unzip jq ripgrep vim git wget curl \
      mtr netcat-openbsd iproute2 lsof nftables bind9-dnsutils \
      supervisor gosu file tree less uuid xxd tmux gh openssh-server && \
    update-ca-certificates
# iptables

RUN bash /opt/scripts/install_tools.sh

RUN pip install --no-cache-dir --upgrade pip wheel setuptools uv && \
    pip install --no-cache-dir --upgrade flake8 pytest \
      pysocks "requests[socks]" "httpx[socks]" pyyaml pydantic pydotenv

RUN npm install -g npm@latest && \
    npm install -g typescript ts-node @types/node zx vitest execa pnpm yarn && \
    rm -rf ~/.npm ~/.cache

#### 3. build
# userdel -r ubuntu || true
RUN groupadd -g $user_gid appuser && \
    useradd -s /bin/bash -m -u $user_uid -g $user_gid appuser

USER appuser
WORKDIR /home/appuser

COPY --chown=appuser:appuser copy_files/bash_aliases /home/appuser/.bash_aliases
COPY --chown=appuser:appuser copy_files/bash_profile /home/appuser/.bash_profile
ADD --chown=appuser:appuser ./copy_files/vimrc .vimrc

RUN curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#### 4. container
ENV https_proxy="" \
    http_proxy="" \
    no_proxy=""

# ENV NPM_CONFIG_PREFIX=$HOME/.local/npm
RUN npm config set prefix ~/.local/npm
ENV PATH=/home/appuser/.local/bin:/home/appuser/.local/npm/bin:$PATH
# npm config list -l
# python3 -m venv ~/apps/venv

RUN mkdir -p .config .cache .local/share .local/state apps workspace

VOLUME /home/appuser/.cache
VOLUME /home/appuser/.config
VOLUME /home/appuser/.local/share
VOLUME /home/appuser/.local/state

VOLUME /home/appuser/apps
VOLUME /home/appuser/workspace

WORKDIR /home/appuser/workspace

ENTRYPOINT ["/opt/scripts/entrypoint.sh"]
CMD ["sleep", "infinity"]
