networks:
  net: { name: openclaw, driver: bridge, external: false }

services:
  openclaw:
    image: local/openclaw:latest
    restart: always # unless-stopped
    container_name: openclaw
    hostname: openclaw
    cap_add: [NET_ADMIN]
    devices: [/dev/net/tun:/dev/net/tun]
    extra_hosts:
      host.docker.internal: host-gateway
    deploy:
      resources:
        limits:
          cpus: "1.50"
          memory: 2048M
        reservations:
          cpus: "0.50"
          memory: 1024M
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:18789/healthz || exit 1"]
      # test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:18789/readyz || exit 1"]
      start_period: 30s
      interval: 15s
      timeout: 3s
      retries: 5

    #network_mode: bridge
    networks: [net]
    ports: [127.0.0.1:18789:18789]
    user: root:root
    volumes:
    volumes:
    - ./data/config:/home/appuser/.config
    - ./data/cache:/home/appuser/.cache
    - ./data/share:/home/appuser/.local/share
    - ./data/state:/home/appuser/.local/state
    - ./data/apps:/home/appuser/apps
    - ./data/workspace:/home/appuser/workspace

    - ./data/openclaw:/home/appuser/.openclaw
    - ./logs:/tmp/openclaw
    - ./data/site-packages:/home/appuser/.local/lib/python3.14/site-packages
    environment:
      TZ: Asia/Shanghai
      OPENCLAW_NO_RESPAWN: "1"
      # https_proxy: http://172.17.0.1:1080
      # http_proxy: http://172.17.0.1:1080
      # no_proxy: localhost,127.0.0.1,::1,192.168.0.0/16,10.0.0.0/8,172.16.0.1/12,.svc,.lan,.local,.test,.internal
    entrypoint: []
    command: ["supervisord", "-l", "logs/supervisord.log", "-c", "configs/supervisord.conf"]
