services:
  openclaw:
    image: local/openclaw:latest
    restart: always
    container_name: openclaw
    hostname: openclaw
    network_mode: bridge
    #networks: [net]
    ports: [18789:18789]
    user: appuser:appuser
    volumes:
    - ./data/xdg:/home/appuser/xdg
    - ./data/openclaw:/home/appuser/.openclaw
    environment:
      TZ: Asia/Shanghai
      # https_proxy: http://172.17.0.1:1080
      # http_proxy: http://172.17.0.1:1080
      # no_proxy: ""
      # TOKEN: xxxxxx
      # ALLOWED_ORIGINS: '["http://localhost:18789","http://127.0.0.1:18789"]'
    command: ["openclaw", "gateway", "--port=18789"]
    #$ openclaw onboard --install-daemon
