FROM q.local/openclaw:latest

USER appuser

RUN /opt/scripts/apt_install.sh

RUN npm install -g "openclaw@$latest" && \
    mkdir -p ~/.openclaw ~/.agents && \
    rm -rf ~/.npm ~/.cache

RUN mkdir -p ~/.cache
