FROM ubuntu:24.04

COPY bin /opt/bin

ENV TZ=Asia/Shanghai

RUN bash /opt/bin/apt_install.sh tzdata file
# python3 python3-pip supervisor podman

RUN userdel -r ubuntu || true

#RUN useradd -m -s /bin/bash -u 1000 -g 1000 appuser
#USER appuser
RUN mkdir -p /home/appuser/workspace

VOLUME ["/home/appuser/workspace"]
WORKDIR /home/appuser/workspace

ENTRYPOINT ["/opt/bin/entrypoint.sh"]
CMD ["echo", "You are already in the container"]
