#preferred_auth_method = "apikey"
#forced_login_method = "api"

model = "deepseek-v4-pro"
model_provider = "deepseek"
model_reasoning_effort = "high"
model_catalog_json = "/home/appuser/.local/share/codex/deepseek-models.json"

[model_providers.deepseek]
name = "deepseek"
base_url = "https://api.deepseek.com/"
wire_api = "responses"
experimental_bearer_token = "<DeepSeek API Key>"
