networks:
  net: { name: local, driver: bridge, external: false }

services:
  node:
    image: q.local/agents:latest
    restart: always
    container_name: node
    hostname: node
    #network_mode: bridge
    networks: [net]
    ports: [127.0.0.1:8080:8080]
    user: appuser:appuser
    volumes:
    - ./data/config:/home/appuser/.config
    - ./data/cache:/home/appuser/.cache
    - ./data/share:/home/appuser/.local/share
    - ./data/state:/home/appuser/.local/state
    - ./data/apps:/home/appuser/apps
    - ./data/workspace:/home/appuser/workspace
    environment:
      TZ: Asia/Shanghai
      # https_proxy: http://172.17.0.1:1080
      # http_proxy: http://172.17.0.1:1080
      # no_proxy: ""
    command: ["sleep", "infinity"]
