# Dockerfile
# FROM node:20-alpine AS builder
FROM node:lts-alpine AS builder

LABEL stage=vue-web_builder

ARG BASE

WORKDIR /apps

RUN echo "==> BASE: ${BASE}"

# *.env.* index.html
ADD  *.js *.json  ./
COPY public/ ./public
COPY src/ ./src

COPY cache.local ./cache.local
RUN cp cache.local/env ./.env

RUN if [ -d ./cache.local/node_modules ]; then \
    echo "==> Found ./cache.local/node_modules"; \
    mv ./cache.local/node_modules ./; \
  fi

# npm config set registry https://registry.npmmirror.com
RUN npm install --registry=https://registry.npmmirror.com &> /dev/null

RUN npm run build -- --dest ${BASE}

ADD cache.local/build.json ${BASE}/build.json

####
FROM nginx:1-alpine

WORKDIR /apps
ADD cache.local/build.yaml ./

COPY --from=builder /apps/target ./target

RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bk; \
  sed -i '/worker_processes/s#auto#4#' /etc/nginx/nginx.conf

COPY containers/static.nginx.conf /etc/nginx/conf.d/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
