FROM alpine:3

ARG region
ARG KAFKA_Version
ARG SCALA_Version

ENV KAFKA_Version=${KAFKA_Version}
ENV SCALA_Version=${SCALA_Version}

COPY bin /apps/bin
# RUN chmod a+x /apps/bin/*.sh

RUN if [ "$region" = "cn" ]; then \
    echo "==> region: $region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade && \
  apk --no-cache add tzdata bash yq openjdk21

RUN tag=${SCALA_Version}-${KAFKA_Version}; \
  apk --no-cache add wget && \
  wget https://downloads.apache.org/kafka/${KAFKA_Version}/kafka_${tag}.tgz && \
  tar -xf kafka_${tag}.tgz && \
  mv kafka_${tag} /opt/kafka && \
  rm kafka_${tag}.tgz && \
  apk del wget
# mkdir -p /opt/kafka && tar -xf kafka_${tag}.tgz --strip-components=1 -C /opt/kafka

RUN mkdir -p /apps/kafka/data /apps/kafka/logs && ln -s /apps/kafka/logs /opt/logs

ENV PATH=/opt/kafka/bin:$PATH
WORKDIR /apps

EXPOSE 9092 9093
# ENTRYPOINT ["/apps/bin/entrypoint.sh"]
CMD ["/apps/bin/entrypoint.sh"]
