networks:
  net: { name: local, external: true }

services:
  mattermost:
    #image: mattermost/mattermost-team-edition:release-11
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    restart: unless-stopped
    #depends_on: ["postgres"]
    expose: ["8065"]
    networks: ["net"]
    ports: ["8065:8065"]
    volumes:
    - ./data/mattermost/config:/mattermost/config
    - ./data/mattermost/data:/mattermost/data
    - ./data/mattermost/logs:/mattermost/logs
    - ./data/mattermost/plugins:/mattermost/plugins
    - ./data/mattermost/client/plugins:/mattermost/client/plugins
    - ./data/mattermost/bleve-indexes:/mattermost/bleve-indexes
    environment:
      TZ: ${TZ}
      MM_SERVICESETTINGS_SITEURL: https://mattermost.example.com
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mmuser:change_this_strong_password@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
      MM_SERVICESETTINGS_LISTENADDRESS: ":8065"
      #CERT_PATH: ./certs/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
      #KEY_PATH: ./certs/etc/letsencrypt/live/${DOMAIN}/privkey.pem
