[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:hysteria]
user=appuser
command=hysteria client -c /app/configs/hysteria.client.yaml
directory=/app
autostart=true
autorestart=true
startsecs=2
stopsignal=TERM
stopwaitsecs=10
stdout_logfile=/app/logs/hysteria.log
stderr_logfile=/app/logs/hysteria.error
