# path: ~/.bash_aliases

alias sh='bash'
alias ll='ls -al'
alias tree1='tree -L 1'; alias tree2='tree -L 2'; alias tree3='tree -L 3'
alias ..='cd ../'; alias ...='cd ../../'; alias ....='cd ../../../'

for d in "$HOME/.local/bin" "$HOME/apps/bin"; do
    if [ ! -d "$d" ]; then
        continue
    fi

    case ":${PATH}:" in
    *:"$d":*)
        ;;
    *)
        export PATH="$d:$PATH"
        ;;
    esac
done


for d in $(ls -d $HOME/.local/*/bin/ $HOME/apps/*/bin/ 2>/dev/null); do
    d=${d%/}

    if [[ ":$PATH:" != *":$d:"* ]]; then
        export PATH="$d:$PATH"
    fi
done


if [ -s $HOME/apps/apps.aliases ]; then
    . $HOME/apps/apps.aliases
fi
