FROM local/3dgrut:base

RUN DEBIAN_FRONTEND=nointeractive apt update && apt install -y xvfb colmap

RUN mkdir -p /root/.cache/torch/hub/checkpoints/ && \
  wget https://download.pytorch.org/models/vgg16-397923af.pth \
  -O /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth

#ENTRYPOINT ["sleep", "infinity"]

CMD ["sleep", "infinity"]
