server {
	listen       80;
	server_name  ____SERVER_NAME____;
	return       301 https://$host$request_uri;
}

server {
	listen         443 ssl;
	server_name    ____SERVER_NAME____;
	http2          on;
	charset        utf-8;
	server_tokens  off;

	gzip on;
	gzip_vary on;
	gzip_min_length 1k;
	gzip_comp_level 5;
	gzip_types
	    text/plain
	    text/css
	    text/xml
	    text/javascript
	    text/markdown
	    application/json
	    application/javascript
	    application/xml
	    application/xml+rss
	    image/svg+xml;

	client_max_body_size     100m;
	client_body_buffer_size  16k;

	access_log  /path/to/nginx/logs/____SERVER_NAME____.log;
	error_log   /path/to/nginx/logs/____SERVER_NAME____.error;


	#location /dufs/public/ {
	#	proxy_pass http://127.0.0.1:5000/public/;
	#}

	location / {
		proxy_pass         http://127.0.0.1:5000/;
		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Host $host;

		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Real-IP $remote_addr;

		#proxy_set_header Upgrade $http_upgrade;
		#proxy_set_header Connection "upgrade";

		proxy_read_timeout 3600;
		proxy_send_timeout 3600;

		# WebDAV
		proxy_set_header Destination $http_destination;
		proxy_set_header Overwrite $http_overwrite;
		proxy_set_header Depth $http_depth;
	}



	ssl_certificate      /path/to/nginx/certs/fullchain.cer;
	ssl_certificate_key  /path/to/nginx/certs/domain.key;
	ssl_session_cache    shared:SSL:1m;
	ssl_session_timeout  5m;
	ssl_protocols        TLSv1.2 TLSv1.3;

	ssl_prefer_server_ciphers  on;

	ssl_ciphers          ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
}
