#!/bin/expect
set prompt "#"
set timeout 60

# read from stdin
# expect_user -re "(.*)\n"
# set input $expect_out(1,string)

# set password "DontUseThisPassword"
# set username [lindex $argv 0];
# set password [lindex $argv 1];

set fh [open "./configs/app.secret" r]
set password [read -nonewline $fh]
close $fh

spawn docker exec -it app connect

expect "Enter password:"
send "$password\r"
interact

# expect eof
