FROM ubuntu:24.04

ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

COPY copy_files/bin /opt/bin

ENV TZ=Asia/Shanghai

RUN bash /opt/bin/apt_install.sh tzdata ca-certificates file locales gosu && \
    update-ca-certificates && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8
#/opt/bin/apt_install.sh build-essential gosu podman \
#  python3 python3-venv python3-pip python3-dev supervisor \
#  libgl1 libglib2.0-0t64 fonts-noto-cjk
#locale-gen zh_CN.UTF-8

RUN userdel -r ubuntu || true

#RUN useradd -m -s /bin/bash -u 1000 -g 1000 appuser
#USER appuser

RUN mkdir -p /home/appuser/workspace
VOLUME ["/home/appuser/workspace"]
WORKDIR /home/appuser/workspace

ENV http_proxy="" \
    https_proxy="" \
    no_proxy=""

ENTRYPOINT ["/opt/bin/entrypoint.sh"]
CMD ["echo", "You are already in the container"]
