FROM alpine/java:21-jre

ARG KAFKA_Version
ARG SCALA_Version
ARG region

ENV KAFKA_Version=${KAFKA_Version}
ENV SCALA_Version=${SCALA_Version}

ADD entrypoint.sh /opt/
WORKDIR /apps

RUN if [ "$region" = "cn" ]; then \
    echo "==> region: $region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade && \
  apk --no-cache add tzdata bash yq wget
# openjdk21 or openjdk21-jre

RUN tag=${SCALA_Version}-${KAFKA_Version}; \
  wget https://downloads.apache.org/kafka/${KAFKA_Version}/kafka_${tag}.tgz && \
  tar -xf kafka_${tag}.tgz && \
  mv kafka_${tag} /opt/kafka && \
  rm kafka_${tag}.tgz

# mkdir -p /opt/kafka && tar -xf kafka_${tag}.tgz --strip-components=1 -C /opt/kafka

RUN mkdir -p /apps/data/kafka

ENV PATH=/opt/kafka/bin:$PATH

VOLUME ["/apps/data/kafka", "/opt/kafka/logs"]

EXPOSE 9092 9093
# ENTRYPOINT ["/apps/bin/entrypoint.sh"]
CMD ["/opt/entrypoint.sh"]
