#networks:
#  net: { name: openclaw-tunnel, driver: bridge, external: false }

services:
  openclaw-tunnel:
    image: local/openclaw-tunnel:latest
    restart: always # unless-stopped
    container_name: openclaw-tunnel
    hostname: openclaw-tunnel
    cap_add: [NET_ADMIN]
    devices: [/dev/net/tun:/dev/net/tun]
    extra_hosts:
      host.docker.internal: host-gateway
    deploy:
      resources:
        limits:
          cpus: "1.50"
          memory: 1024M
        reservations:
          cpus: "0.50"
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:18789/healthz || exit 1"]
      # test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:18789/readyz || exit 1"]
      start_period: 30s
      interval: 15s
      timeout: 3s
      retries: 5

    network_mode: bridge
    #networks: [net]
    ports: [127.0.0.1:18789:18789]
    user: root:root
    #user: appuser:appuser
    volumes:
    - ./data/xdg:/home/appuser/xdg
    - ./data/xdg/config:/home/appuser/.config
    - ./data/xdg/cache:/home/appuser/.cache
    - ./data/xdg/share:/home/appuser/.local/share
    - ./data/xdg/state:/home/appuser/.local/state
    - ./data/apps:/home/appuser/apps
    - ./data/workspace:/home/appuser/workspace

    - ./configs:/home/appuser/workspace/configs:ro
    - ./logs:/home/appuser/workspace/logs
    - ./data/openclaw:/home/appuser/.openclaw
    - ./logs:/tmp/openclaw
    - ./data/site-packages:/home/appuser/.local/venv/lib/python3.13/site-packages
    environment:
      TZ: Asia/Shanghai
      # https_proxy: http://172.17.0.1:1080
      # http_proxy: http://172.17.0.1:1080
      # no_proxy: localhost,127.0.0.1,::1,192.168.0.0/16,10.0.0.0/8,172.16.0.1/12,.svc,.lan,.local,.test,.internal
      # OPENCLAW_TOKEN: xxxxxx
      # OPENCLAW_ALLOWED_ORIGINS: '["http://localhost:18789","http://127.0.0.1:18789"]'
    command: ["supervisord", "-l", "logs/supervisord.log", "-c", "configs/supervisord.conf"]
    #command: ["openclaw", "gateway", "run", "--port=18789"]
