services:
  hysteria:
    image: tobyxdd/hysteria:v2
    container_name: hysteria
    restart: always
    network_mode: "host"
    volumes:
    - ./configs/hysteria.yaml:/app/config/hysteria.yaml
    #- ./data/acme:/acme
    command: ["server", "-c", "/app/config/hysteria.yaml"]
