services:
  hysteria:
    image: tobyxdd/hysteria:v2
    container_name: hysteria
    restart: always
    network_mode: "host"
    volumes:
    - ./configs//hysteria.yaml:/etc/hysteria.yaml
    - ./data/acme:/acme
    command: ["server", "-c", "/etc/hysteria.yaml"]
