FROM alpine:3

ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

ARG TARGET_OS=linux
ARG TARGET_ARCH=amd64

COPY copy_files/scripts /opt/scripts

RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk add --no-cache tzdata coreutils supervisor gosu ca-certificates curl bash \
      bind-tools tcpdump nmap iproute2 && \
    update-ca-certificates

#    arch="${TARGET_ARCH}";
#    case "$arch" in
#      amd64) bin="hysteria-linux-amd64" ;;
#      arm64) bin="hysteria-linux-arm64" ;;
#      *) echo "Unsupported arch: ${TARGET_ARCH}" && exit 1 ;;
#    esac;

# url="https://github.com/apernet/hysteria/releases/download/${HYSTERIA_VERSION}/${bin}";

RUN url="https://github.com/apernet/hysteria/releases/latest/download/hysteria-linux-amd64"; \
    echo "Downloading: $url"; \
    mkdir -p /opt/bin && \
    curl -fsSL "$url" -o /usr/local/bin/hysteria && \
    chmod a+x /usr/local/bin/hysteria && \
    hysteria version

RUN mkdir -p /app/examples
ADD examples/. /app/examples/

WORKDIR /app

ENV http_proxy="" \
    https_proxy="" \
    no_proxy="" \
    APPUSER_UID="0" \
    APPUSER_GID="0"

EXPOSE 443/udp
EXPOSE 1080/tcp
EXPOSE 1081/tcp

ENTRYPOINT ["/opt/scripts/entrypoint.sh"]
CMD ["supervisord", "-c", "configs/supervisord.server.conf"]
#CMD ["supervisord", "-c", "configs/supervisord.client.conf"]
