[supervisord]
nodaemon=true
logfile=/home/appuser/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:sing-box]
user=root
command=sing-box run -c /home/appuser/configs/sing-box.tun.json
directory=/home/appuser/workspace
autostart=true
autorestart=true
startsecs=2
stopsignal=TERM
stopwaitsecs=10
#stdout_logfile=/home/appuser/logs/sing-box.log
#stderr_logfile=/home/appuser/logs/sing-box.error

[program:sleep]
user=appuser
command=sleep infinity
directory=/home/appuser/workspace
autostart=true
autorestart=true
startsecs=2
stopsignal=TERM
stopwaitsecs=10
#stdout_logfile=/home/appuser/logs/sleep.log
#stderr_logfile=/home/appuser/logs/sleep.error
