# Dockerfile
# FROM node:20-alpine AS builder
FROM node:lts-alpine AS builder

LABEL stage=vue-web_builder

ARG VUE_APP_PUBLIC_PATH

WORKDIR /apps

# *.env.* index.html
ADD  *.js *.json  ./
COPY public/ ./public
COPY src/ ./src

COPY cache.local ./cache.local
RUN cp cache.local/env ./.env

RUN if [ -d ./cache.local/node_modules ]; then \
    echo "==> Found ./cache.local/node_modules"; \
    mv ./cache.local/node_modules ./; \
  fi

# npm config set registry https://registry.npmmirror.com
RUN npm install --registry=https://registry.npmmirror.com &> /dev/null
# RUN node_modules/.bin/vue-cli-service build --mode ${mode}

RUN npm run build

####
FROM nginx:1-alpine

ARG VUE_APP_PUBLIC_PATH

WORKDIR /apps
ADD cache.local/build.yaml ./

COPY --from=builder /apps/dist ./dist

RUN echo "==> VUE_APP_PUBLIC_PATH: $VUE_APP_PUBLIC_PATH"; \
  path=${VUE_APP_PUBLIC_PATH%/}; path=${path%/}; \
  mkdir -p static; \
  mv dist/index.html static/; \
  if [ -z "$pp" ]; then mv dist/* static/; rmdir dist; else mv dist static/$pp; fi

RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bk; \
  sed -i '/worker_processes/s#auto#4#' /etc/nginx/nginx.conf

COPY deployments/static.nginx.conf /etc/nginx/conf.d/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
