FROM python:3.12-slim AS builder

WORKDIR /opt

COPY pip pip

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get upgrade -y --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple && \
  pip install --no-cache-dir -r pip/gradio.pip.txt \
  -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN mkdir -p configs data logs

ENV APP_ARGS="--config=configs/local.yaml"

VOLUME ["/opt/data", "/opt/configs", "/opt/logs"]
EXPOSE 7860

CMD ["gunicorn", "-k=uvicorn.workers.UvicornWorker", "--bind=0.0.0.0:7860", "main:app"]
