services:
  opencode:
    image: local/opencode:latest
    restart: always
    container_name: opencode
    hostname: opencode
    network_mode: bridge
    #networks: [net]
    ports: ["127.0.0.1:4096:4096"] # "127.0.0.1:1455:1455"
    user: appuser:appuser
    volumes:
    - ./data/apps:/home/appuser/apps
    - ./data/workspace:/home/appuser/workspace
    - ./data/xdg:/home/appuser/xdg
    - ./data/xdg/config:/home/appuser/.config
    - ./data/xdg/cache:/home/appuser/.cache
    - ./data/xdg/share:/home/appuser/.local/share
    - ./data/xdg/state:/home/appuser/.local/state

    - ./data/gemini:/home/appuser/.gemini
    - ./data/codex:/home/appuser/.codex
    environment:
      TZ: Asia/Shanghai
      # https_proxy: http://127.0.0.1:1080
      # http_proxy: http://127.0.0.1:1080
      # no_proxy: ""
      # OPENCODE_SERVER_USERNAME: opencode
      # OPENCODE_SERVER_PASSWORD: ""
    command: ["opencode", "web", "--hostname=0.0.0.0", "--port=4096"]
    #command: ["opencode", "/path/to/project/with_tui"]
    #command: [sleep, infinity]
