FROM local/opencode:latest

USER root
RUN apt_install.sh

UEER appuser
WORKDIR /home/appuser

#RUN npm install -g opencode-ai@latest
RUN npm update -g opencode-ai@latest

WORKDIR /home/appuser/workspace
