FROM local/agents:24-trixie

####
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

ARG build_region

USER root
COPY ./copy_files/scripts/. /opt/scripts

####
# ENV OPENCODE_SERVER_USERNAME="opencode"
# CODEX_HOME=~/.codex
# OPENCODE_CONFIG_DIR=~/.config/opencode
# OPENCODE_SERVER_PASSWORD=""

USER appuser
WORKDIR /home/appuser

ADD --chown=appuser:appuser ./copy_files/vimrc .vimrc

RUN if [ "$build_region" == "cn" ]; then \
        bash /opt/scripts/config_cn.sh pip; \
        bash /opt/scripts/config_cn.sh npm; \
    fi

####
RUN pip install --no-cache pyright

ENV CLAUDE_CONFIG_DIR=/home/appuser/apps/claude

RUN npm install -g opencode-ai@latest oh-my-opencode@latest \
      @fission-ai/openspec@latest @openai/codex @google/gemini-cli && \
    npm install -g bash-language-server yaml-language-server markdownlint-cli && \
    rm -rf ~/.npm ~/.cache

# opencode --version | awk '{print "opencode: "$1}'
# openspec --version | awk '{print "openspec: "$1}'
# codex --version | awk '{print "codex: "$2}'
# gemini --version | awk '{print "gemini-cli: "$1}'

# curl -fsSL https://opencode.ai/install | bash
# npx -y oh-my-opencode install
# npm list -g --depth=0

RUN npm config set prefix ~/apps/npm
# npm config list -l
# python3 -m venv ~/apps/venv

####
ENV https_proxy="" \
    http_proxy="" \
    no_proxy=""

VOLUME /home/appuser/apps
WORKDIR /home/appuser/workspace

# webui: 4096, auth_callback: 1455
EXPOSE 4096

ENTRYPOINT []
# opencode webui
CMD ["opencode", "web", "--hostname=0.0.0.0", "--port=4096"]
# --cors http://localhost:4096 --cors https://app.example.com
# Works exclusively on the host network model: --mdns fase --mdns-domain opencode.local

# opencode tui
#CMD ["opencode"]
