FROM local/pyjs:trixie

####
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

ARG build_region

USER root
COPY ./copy_files/scripts/. /opt/scripts

####
# OPENCODE_SERVER_USERNAME="opencode"
# OPENCODE_CONFIG_DIR=~/.config/opencode
# OPENCODE_SERVER_PASSWORD=""

RUN /opt/scripts/apt_install.sh dos2unix bash-completion \
      sqlite3 postgresql-client \
      ripgrep fd-find bat sd && \
      ln -s /usr/bin/batcat /usr/bin/bat

RUN tag_name=$(curl -fsSL https://api.github.com/repos/Wilfred/difftastic/releases/latest | jq -r .tag_name) && \
    curl -fL -o difft.tar.gz \
      "https://github.com/Wilfred/difftastic/releases/download/$tag_name/difft-x86_64-unknown-linux-gnu.tar.gz" && \
    tar -xf difft.tar.gz -C /usr/local/bin/ && \
    rm -rf difft.tar.gz

# https://github.com/eza-community/eza/releases/download/v0.23.4/eza_x86_64-unknown-linux-gnu.tar.gz
RUN curl -fL -o eza.tar.gz "https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz" && \
    tar -xf eza.tar.gz -C /usr/local/bin/ && \
    chmod a+x /usr/local/bin/eza && \
    rm -f eza.tar.gz

RUN pip install --no-cache-dir --upgrade \
      python-docx python-pptx openpyxl pandas \
      pypdf pdfplumber pymupdf \
      ast-grep-cli

USER appuser
WORKDIR /home/appuser

ADD --chown=appuser:appuser ./copy_files/vimrc .vimrc

RUN if [ "$build_region" == "cn" ]; then \
        bash /opt/scripts/config_cn.sh pip; \
        bash /opt/scripts/config_cn.sh npm; \
    fi

####
#RUN pip install --no-cache pyright
#RUN npm install -g opencode-ai@latest oh-my-opencode@latest

RUN mkdir -p ~/.local/bin && \
    curl -fsSL https://opencode.ai/install | bash && \
    mv ~/.opencode/bin/opencode ~/.local/bin/ && \
    rm -r ~/.opencode

RUN npm install -g oh-my-opencode-linux-x64@latest && \
    rm -rf ~/.npm ~/.cache

RUN npm install -g markdownlint-cli bash-language-server yaml-language-server \
      pyright vscode-langservers-extracted typescript typescript-language-server \
      @vue/language-server eslint prettier prettier-plugin-tailwindcss && \
    rm -rf ~/.npm ~/.cache

# opencode --version | awk '{print "opencode: "$1}'
# openspec --version | awk '{print "openspec: "$1}'
# codex --version | awk '{print "codex: "$2}'
# gemini --version | awk '{print "gemini-cli: "$1}'
# curl -fsSL https://opencode.ai/install | bash
# npx -y oh-my-opencode install --no-tui --claude=no --openai=no --gemini=no --copilot=no

####
ENV https_proxy="" \
    http_proxy="" \
    no_proxy=""

WORKDIR /home/appuser/workspace

# webui: 4096, auth_callback: 1455
EXPOSE 4096

ENTRYPOINT []

# opencode webui
CMD ["opencode", "web", "--hostname=0.0.0.0", "--port=4096"]
# --cors http://localhost:4096 --cors https://app.example.com
# Works exclusively on the host network model: --mdns fase --mdns-domain opencode.local

# opencode tui
#CMD ["opencode"]
