FROM local/pyjs:trixie

#### 1. parsing args
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

ARG build_region

#### 2. root
USER root
COPY ./copy_files/scripts/. /opt/scripts

RUN bash /opt/scripts/_install_tools.sh

#### 3. appuser
# OPENCODE_SERVER_USERNAME="opencode"
# OPENCODE_CONFIG_DIR=~/.config/opencode
# OPENCODE_SERVER_PASSWORD=""

USER appuser
WORKDIR /home/appuser

ADD --chown=appuser:appuser ./copy_files/vimrc .vimrc

RUN if [ "$build_region" == "cn" ]; then \
        bash /opt/scripts/config_cn.sh pip; \
        bash /opt/scripts/config_cn.sh npm; \
    fi

#### 3. installation
RUN mkdir -p ~/.local/bin && \
    curl -fsSL https://opencode.ai/install | bash && \
    mv ~/.opencode/bin/opencode ~/.local/bin/ && \
    rm -r ~/.opencode

RUN npm install -g markdownlint-cli bash-language-server yaml-language-server \
      pyright vscode-langservers-extracted typescript typescript-language-server \
      @vue/language-server eslint prettier prettier-plugin-tailwindcss && \
    rm -rf ~/.npm ~/.cache

RUN mkdir -p ~/.cache

#### 3. container
ENV https_proxy="" \
    http_proxy="" \
    no_proxy=""

WORKDIR /home/appuser/workspace

# webui: 4096, auth_callback: 1455
EXPOSE 4096

ENTRYPOINT []

# opencode webui
CMD ["opencode", "web", "--hostname=0.0.0.0", "--port=4096"]
# --cors http://localhost:4096 --cors https://app.example.com
# Works exclusively on the host network model: --mdns fase --mdns-domain opencode.local

# opencode tui
#CMD ["opencode"]
