FROM alpine:3

ARG APP_Name
ARG APP_Version
ARG region

MAINTAINER github.com/d2jvkpn <d2jvkpn@noreply.local>
LABEL app=${APP_Name}
LABEL version=${APP_Version}

ENV APP_Name=${APP_Name}
ENV APP_Version=${APP_Version}
ENV TZ=${TZ:-Asia/Shanghai}

RUN mkdir -p /apps/configs /apps/data /apps/logs
WORKDIR /apps

RUN if [ "$region" = "cn" ]; then \
    echo "==> BUILD_Region: $BUILD_Region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade && \
  apk --no-cache add tzdata coreutils \
    curl bash yq gosu \
    openssl iproute2
  # vim jq gcompat supervisor nmap logroate openvpn openssh

VOLUME ["/apps/configs", "/apps/data", "/apps/logs"]
CMD ["sleep", "infinity"]
