[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/product-variant
data_dir = /var/lib/odoo
db_host = postgres
db_user = odoo
db_name = odoo
db_password = <password>
db_port = 5432
....
