FROM kylemanna/openvpn:latest

ARG BUILD_Region

WORKDIR /apps

RUN mkdir -p target logs
ADD containers/openvpn_logrotate.sh target/
RUN chmod a+x target/*.sh

# https://crontab.guru/#0_0_*_*_1
RUN crontab -l > /etc/crontab.bk && \
  echo "0 0 * * 1 bash /apps/target/openvpn_logrotate.sh" > temp.crontab && \
  crontab temp.crontab && \
  rm temp.crontab

RUN if [ "$BUILD_Region" = "cn" ]; then \
    echo "==> BUILD_Region: $BUILD_Region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade && \
  apk --no-cache add supervisor coreutils tzdata

RUN cp /etc/supervisord.conf /etc/supervisord.conf.bk
ADD containers/supervisord.conf /etc/supervisord.conf
ADD containers/supervisor.ini /etc/supervisor.d/

CMD [supervisord, -l, /apps/logs/supervisord.log, -c, /etc/supervisord.conf]
