FROM kylemanna/openvpn:latest

ARG BUILD_Region

WORKDIR /apps

RUN mkdir -p target logs
ADD containers/openvpn_logrotate.sh target/
RUN chmod a+x target/*.sh

# https://crontab.guru/#0_0_*_1_*
RUN crontab -l > /etc/crontab.bk && \
  echo "0 0 * 1 * bash /apps/target/openvpn_logrotate.sh yesterday" > /tmp/crontab && \
  crontab /tmp/crontab

RUN if [ "$BUILD_Region" = "cn" ]; then \
    echo "==> BUILD_Region: $BUILD_Region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade && \
  apk --no-cache add supervisor coreutils tzdata nginx

RUN cp /etc/supervisord.conf /etc/supervisord.conf.bk
ADD containers/supervisord.conf /etc/supervisord.conf
ADD containers/supervisor.ini /etc/supervisor.d/

CMD [supervisord, -l, /apps/logs/supervisord.log, -c, /etc/supervisord.conf]
# CMD: [openvpn, --auth-nocache, --config, configs/client.ovpn, --askpass, configs/client.ovpn.pass]
# CMD: [openvpn, --auth-nocache, --config, configs/client.ovpn, --auth-user-pass, configs/client.ovpn.auth]
# CMD: [supervisord, -l, /apps/logs/supervisord.log, -c, /app/supervisord.nginx.conf]
