# path: ~/.bash_aliases

# $HOME/.config
export XDG_CONFIG_HOME=$HOME/xdg/config

# $HOME/.cache
export XDG_CACHE_HOME=$HOME/xdg/cache

# $HOME/.local/share
export XDG_DATA_HOME=$HOME/xdg/share

# $HOME/.local/state
export XDG_STATE_HOME=$HOME/xdg/state


for d in "$HOME/.local/bin" "$HOME/apps/bin"; do
    if [ ! -d "$d" ]; then
        continue
    fi

    case ":${PATH}:" in
    *:"$d":*)
        ;;
    *)
        export PATH="$d:$PATH"
        ;;
    esac
done


for d in $(ls -d $HOME/.local/*/bin/ $HOME/apps/*/bin/ 2>/dev/null); do
    d=${d%/}

    if [[ ":$PATH:" != *":$d:"* ]]; then
        export PATH="$d:$PATH"
    fi
done


if [ -f $HOME/apps/apps.env ]; then
    . $HOME/apps/apps.env
fi
