# path: ~/.bash_aliases

for d in "$HOME/.local/bin" "$HOME/apps/bin"; do
    if [ ! -d "$d" ]; then
        continue
    fi

    case ":${PATH}:" in
    *:"$d":*)
        ;;
    *)
        export PATH="$d:$PATH"
        ;;
    esac
done


for d in $(ls -d $HOME/.local/*/bin/ $HOME/apps/*/bin/ 2>/dev/null); do
    d=${d%/}

    if [[ ":$PATH:" != *":$d:"* ]]; then
        export PATH="$d:$PATH"
    fi
done


if [ -f $HOME/apps/apps.env ]; then
    . $HOME/apps/apps.env
fi
