# path: ~/.npmrc

# $ npm config set registry "https://registry.npmmirror.com"
# $ npm config set prefix ~/apps/npm
# $ npm config get userconfig
# $ npm config get registry

prefix=~/apps/npm
#registry=https://registry.npmjs.org/
registry=https://registry.npmmirror.com/
#disturl=https://registry.npmmirror.com/dist
