[supervisord]
nodaemon=true
logfile=/home/appuser/workspace/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

;[inet_http_server]  # inet (TCP) server disabled by default
;port=:9002          # (ip_address:port specifier, *:port for all iface)
;username=user       # (default is no username)
;password=123        # (default is no password)

[program:sing-box]
user=root
directory=/home/appuser/workspace
command=sing-box run -c configs/sing-box.tun.json
autostart=true
autorestart=true
startsecs=2
stopsignal=TERM
stopwaitsecs=10
#stdout_logfile=logs/sing-box.supervisord.log
#stderr_logfile=logs/sing-box.supervisord.error

[program:openvpn]
user=root
#command=openvpn --auth-nocache --config configs/client.ovpn --auth-user-pass configs/client.ovpn.auth
command=openvpn --auth-nocache --config configs/client.ovpn --askpass configs/client.ovpn.pass
autostart=true
autorestart=true
stopsignal=TERM
stopwaitsecs=5
stdout_logfile=logs/openvpn-client.supervisord.log
stderr_logfile=logs/openvpn-client.supervisord.error

[program:sleep]
user=appuser
directory=/home/appuser/workspace
command=sleep infinity
autostart=true
autorestart=true
startsecs=2
stopsignal=TERM
stopwaitsecs=10
stdout_logfile=logs/sleep.supervisord.log
stderr_logfile=logs/sleep.supervisord.error
environment=HOME="/home/appuser",USER="appuser",LOGNAME="appuser"
