#volumes:
#  redis: { name: redis, driver: local }

#networks:
#  net: { name: "local", driver: bridge, external: false }

services:
  redis:
    image: redis:8-alpine
    restart: always
    user: ${USER_UID}:${USER_GID}
    healthcheck:
      test: ["CMD-SHELL", "REDISCLI_AUTH=$$(cat /run/secrets/redis.pass) redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host
    #networks: ["net"]
    #ports: ["127.0.0.1:${REDIS_Port}:6379"]
    container_name: redis
    deploy:
      resources:
        limits: { cpus: "2", memory: 2G }
        reservations: { cpus: "0.05", memory: 128M }
    environment:
      TZ: Asia/Shanghai
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
      #ALLOW_EMPTY_PASSWORD: yes  # ALLOW_EMPTY_PASSWORD is recommended only for development.
    working_dir: /data
    volumes:
    - ./configs/redis.pass:/run/secrets/redis.pass
    - ./data/redis:/data:rw
    #command: redis-server /etc/redis.conf --loglevel warning --save 300 10 --requirepass d2jvkpn
    #command: redis-server /etc/redis.conf --loglevel warning --appendonly yes --appendfsync everysec --requirepass d2jvkpn
    command: redis-server /data/redis.conf
