# path: /app/configs/redis.conf

bind 0.0.0.0
port 6379
daemonize no

requirepass ${PASSWORD}

dir /app/data
loglevel notice
logfile ""

#### RDB configuration
save 300 10
save 60 1000
dbfilename dump.rdb

#### AOF configuration
appendonly yes
appendfsync everysec
appendfilename "appendonly.aof"

#### AOF + RDB configuration
aof-use-rdb-preamble yes
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

#### limits
proto-max-bulk-len 32mb

#### optional
# io-threads 4
# io-threads-do-reads yes
