set number
set relativenumber
set cursorline
set showmatch
set nowrap
set ruler
set laststatus=2

set autoindent
set smartindent
set hlsearch

set backspace=indent,eol,start
set clipboard=unnamedplus
set mouse=a
set wildmenu
set history=1000
set undofile
set updatetime=300

set encoding=utf-8
set fileencodings=utf-8,gbk,gb2312,ucs-bom,cp936,latin1

syntax on
filetype plugin indent on

set tabstop=4
set shiftwidth=4
" set expandtab

set list
" set listchars=tab:»\ ,space:·,trail:·,eol:$
" set listchars=tab:>-,trail:.,extends:>,precedes:<
set listchars=space:·,tab:——>

call plug#begin('~/.vim/plugged')
Plug 'sheerun/vim-polyglot'
call plug#end()
