FROM n8nio/n8n:stable

USER root

COPY install Containerfile /opt/install

RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk --no-cache add $(cat /opt/install/apt-install.txt)

USER node

RUN mkdir -p apps && \
    python3 -m venv apps/home.venv && \
    source apps/home.venv/bin/activate && \
    pip install --no-cache --upgrade -r /opt/install/pip-install.txt

ENV PATH=/home/node/apps/home.venv/bin:$PATH

#WORKDIR /home/node/workspace
