FROM n8nio/n8n:stable

USER root

COPY install Containerfile /opt/install

RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk --no-cache add $(grep -v "^#" /opt/install/apk_install.txt)

USER node

WORKDIR /home/node

RUN mkdir -p apps && \
    python3 -m venv apps/home.venv && \
    source apps/home.venv/bin/activate && \
    pip install --no-cache --upgrade -r /opt/install/pip_install.txt

VOLUME ["/home/node/.n8n", "/home/node/workspace", "/home/node/apps/bin"]

ENV GENERIC_TIMEZONE=America/New_York \
  PATH=/home/node/apps/home.venv/bin:/home/node/apps/bin:$PATH

WORKDIR /home/node/workspace
