FROM local/comfyui:cuda12.9-base

ARG HTTP_PROXY
ARG HTTPS_PROXY

ENV http_proxy=$HTTP_PROXY \
  https_proxy=$HTTPS_PROXY

USER root

RUN /opt/bin/apt_install.sh

USER appuser

RUN cd /home/appuser/ComfyUI && \
  git fetch --depth=1 origin master && \
  git reset --hard origin/master && \
  git clean -fd && \
  pip install --no-cache-dir -r requirements.txt

ENV http_proxy="" \
  https_proxy=""

#git fetch --all --prune
#git reset --hard origin/main
#git clean -fd
