FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04 AS base

# 1. Accept proxy settings as build arguments
ARG HTTP_PROXY
ARG HTTPS_PROXY

# 2. Set proxy environment variables for the build
ENV http_proxy=$HTTP_PROXY \
  https_proxy=$HTTPS_PROXY \
  DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y --no-install-recommends \
    tzdata locales fonts-noto-cjk \
    ninja-build jq wget curl git git-lfs vim ffmpeg \
    python3 python3-venv python3-pip python3-dev && \
  locale-gen en_US.UTF-8 zh_CN.UTF-8 && \
  update-locale LANG=en_US.UTF-8 && \
  rm -rf /var/lib/apt/lists/*

# 3. Create a venv
RUN python3 -m venv /opt/venv
ENV PATH=/opt/venv/bin:$PATH \
  LANG=en_US.UTF-8

# RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --no-cache-dir --upgrade pip wheel setuptools huggingface_hub[cli]

# 4. Install ComfyUI
RUN pip install --no-cache-dir torch==2.9.0 torchvision==0.24.0 torchaudio==2.9.0 \
  --index-url https://download.pytorch.org/whl/cu128
#pip install --no-cache-dir xformers
#pip install --no-cache-dir --no-build-isolation flash-attn

RUN git clone --branch master --depth 1 --single-branch \
  https://github.com/comfyanonymous/ComfyUI.git /app/ComfyUI && \
  pip install --no-cache-dir -r /app/ComfyUI/requirements.txt

WORKDIR /app/ComfyUI

#git clone https://github.com/Comfy-Org/ComfyUI-Manager.git custom_nodes/ComfyUI-Manager
#pip install --no-cache-dir -r custom_nodes/ComfyUI-Manager/requirements.txt
#mv custom_nodes/ComfyUI-Manager custom_nodes/ComfyUI-Manager.disabled # disable ComfyUI-Manager

# 5. Reset http_proxy and https_proxy
ENV http_proxy="" \
  https_proxy="" \
  TZ=Asia/Shanghai \
  PYTHONPATH=/app/site-packages

# 6. Set VOLUME, HEALTHCHECK, EXPOSE and CMD
VOLUME /root/.cache
VOLUME /app/site-packages
VOLUME /app/ComfyUI/models
VOLUME /app/ComfyUI/custom_nodes
VOLUME /app/ComfyUI/user/default/workflows
VOLUME /app/ComfyUI/input
VOLUME /app/ComfyUI/output

EXPOSE 8188

#HEALTHCHECK --interval=20s --start-period=30s --timeout=1s --retries=3 CMD \
#  curl --fail --silent -I http://localhost:8188/system_stats &> /dev/null
#  # -w "%{http_code}"

ENTRYPOINT []
CMD ["python3", "main.py", "--enable-cors-header", "--listen=0.0.0.0", "--port=8188"]
