FROM python:3.12-slim

COPY ./install /opt/install

RUN bash /opt/install/apt_install.sh git libgl1

RUN git clone --branch master --depth 1 --single-branch \
    https://github.com/comfyanonymous/ComfyUI.git /opt/ComfyUI.git

WORKDIR /opt/ComfyUI.git

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /opt/ComfyUI.git.defaults && \
    cp -r /opt/ComfyUI.git/models /opt/ComfyUI.git/custom_nodes /opt/ComfyUI.git/custom_nodes \
    /opt/ComfyUI.git.defaults/

VOLUME ["/opt/ComfyUI.git/models", "/opt/ComfyUI.git/custom_nodes", "/opt/ComfyUI.git/output"]

CMD ["python", "main.py", "--listen=0.0.0.0", "--port=8188"]
