FROM q.local/pyjs:trixie

#### 1. setup
ARG http_proxy
ARG https_proxy
ARG no_proxy

ARG build_region

ENV http_proxy="$http_proxy" https_proxy="$https_proxy" no_proxy="$no_proxy"

#### 2. installation
USER root

COPY ./copy_files/scripts/. /opt/scripts
RUN bash /opt/scripts/_install_tools.sh
RUN bash /opt/scripts/_install_services.sh

RUN bash /opt/scripts/_install_playwright.sh
ENV PLAYWRIGHT_BROWSERS_PATH=/opt/ms-playwright

#### 3. appuser
USER appuser
WORKDIR /home/appuser

RUN if [ "$build_region" == "cn" ]; then \
        bash /opt/scripts/config_cn.sh pip; \
        bash /opt/scripts/config_cn.sh npm; \
    fi

RUN npm install -g playwright chrome-devtools-mcp@latest && \
    rm -rf ~/.cache ~/.npm && \
    mkdir -p ~/.cache

#### 4. codebox
RUN bash /opt/scripts/_install_codebox.sh
# OPENCODE_SERVER_USERNAME="opencode"
# OPENCODE_CONFIG_DIR=~/.config/opencode
# OPENCODE_SERVER_PASSWORD=""

ENV CLAUDE_CONFIG_DIR=/home/appuser/.local/share/claude \
    OTEL_EXPORTER_OTLP_ENDPOINT="" \
    OTEL_METRICS_EXPORTER="" \
    OTEL_LOGS_EXPORTER="" \
    DISABLE_TELEMETRY=1 \
    DISABLE_ERROR_REPORTING=1 \
    DISABLE_FEEDBACK_COMMAND=1 \
    CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY=1 \
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
# CLAUDE_CONFIG_DIR default: ~/.claude.json, ~/.claude/{backups,cache,downloads}

ENV CODEX_HOME=/home/appuser/.local/share/codex
ENV CC_SWITCH_CONFIG_DIR=/home/appuser/.local/share/cc-switch

#ADD --chown=appuser:appuser target/claw/* ./.local/bin/
#ADD --chown=appuser:appuser copy_files/scripts/claw.sh ./.local/bin/

#### 5. venv and npm
RUN python3 -m venv /home/appuser/apps/venv && \
    mkdir -p /home/appuser/apps/npm && \
    npm config set prefix /home/appuser/apps/npm
# npm config list -l
# export NPM_CONFIG_PREFIX=$HOME/apps/npm

#### 6. post
ENV https_proxy="" http_proxy="" no_proxy=""
ENV BASH_ENV=/home/appuser/.bash_aliases
ENV TZ=Asia/Shanghai

# webui: 4096, ttyd: 7681, ssh: 4222, auth_callback: 1455
EXPOSE 4096
EXPOSE 7681
EXPOSE 4222

WORKDIR /home/appuser/workspace

# opencode webui
CMD ["opencode", "web", "--hostname=127.0.0.1", "--port=4096"]
# --cors http://localhost:4096 --cors https://app.example.com
# Works exclusively on the host network model: --mdns fase --mdns-domain opencode.local

# opencode tui
#CMD ["opencode"]

# claude code
#CMD ["sing-box", "run", "-c=/app/configs/sing-box.tun.json"]
#CMD ["supervisord", "-l", "/app/logs/supervisord.log", "-c", "/app/configs/supervisord.conf"]
