[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:sshd]
user=root
directory=/app
command=/opt/scripts/run_sshd.sh
autostart=true
autorestart=true
startsecs=2
stopsignal=TERM
stopwaitsecs=10
stdout_logfile=/app/logs/sshd.supervisord.log
stderr_logfile=/app/logs/sshd.supervisord.error

[program:ttyd]
user=appuser
directory=/home/appuser/workspace
command=ttyd -W-t fontSize=32 -p 7681 bash --rcfile ~/.bashrc
autostart=true
autorestart=true
startsecs=2
stopsignal=TERM
stopwaitsecs=10
stdout_logfile=/app/logs/ttyd.supervisord.log
stderr_logfile=/app/logs/ttyd.supervisord.error
environment=HOME="/home/appuser",USER="appuser",LOGNAME="appuser"
