create_dirs:
	mkdir -p data/mattermost/config data/mattermost/data data/mattermost/logs \
	  data/mattermost/plugins data/mattermost/client/plugins data/mattermost/bleve-indexes
	sudo chown -R 2000:2000 data/mattermost
