#FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu24.04
FROM nvidia/cuda:12.9.1-cudnn-runtime-ubuntu24.04

ARG HTTP_PROXY
ARG HTTPS_PROXY

ENV http_proxy=$HTTP_PROXY \
  https_proxy=$HTTPS_PROXY \
  TZ=Asia/Shanghai \
  LANG=en_US.UTF-8 \
  PATH=/opt/conda/bin:/home/appuser/workspace/bin:$PATH

#### 1. init
COPY bin /opt/bin
RUN chmod a+x /opt/bin/*.sh

RUN /opt/bin/apt_install.sh \
  tzdata software-properties-common pkg-config ca-certificates gnupg \
  locales fonts-noto-cjk gosu build-essential \
  vim git git-lfs jq zip unzip file tree dos2unix curl wget && \
  locale-gen en_US.UTF-8 zh_CN.UTF-8 && \
  update-locale LANG=en_US.UTF-8
# tini openssh-client nvidia-cuda-toolkit

RUN wget -qO /usr/local/bin/yq \
  https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && \
  chmod +x /usr/local/bin/yq

#### 2. install conda and python
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
  bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
  rm -f Miniconda3-latest-Linux-x86_64.sh && \
  conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
  conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r && \
  conda install python=3.12 -y --quiet && \
  conda clean -afy

#conda init bash # activate conda base env by default
#conda create -n myenv python=3.14 -y
#conda run -n myenv python script.py
#conda install pip
#conda env export > environment.yml

#### 3. pip install
RUN pip3 install --no-cache-dir --upgrade pip wheel setuptools PySocks && \
  pip3 install --no-cache-dir --upgrade -r /opt/bin/pip.txt

#pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
#pip install pandas -i https://pypi.tuna.tsinghua.edu.cn/simple
#pip install --no-cache-dir "torch>=2.9,<3.0" "torchaudio>=2.9,<3.0" "torchvision>=0.24,<0.25" \
#  --index-url https://download.pytorch.org/whl/cu129
#pip install --no-cache-dir xformers
#pip install --no-cache-dir --no-build-isolation flash-attn
#conda install cuda-nvcc -c nvidia && pip install --no-cache-dir flash-attn

#### 4. config
RUN userdel -r ubuntu || true && \
  mkdir -p /home/appuser/workspace /home/appuser/.jupyter && \
  cp /opt/bin/jupyter_lab_config.py /home/appuser/.jupyter/

ENV http_proxy="" \
  https_proxy="" \
  TZ=Asia/Shanghai \
  USER_UID=0 \
  USER_GID=0

#### 5. setup
WORKDIR /home/appuser/workspace
#RUN useradd -m -s /bin/bash -u 1000 -g 1000 appuser
#USER appuser

EXPOSE 8888

VOLUME /home/appuser/workspace
VOLUME /home/appuser/.local/lib/python3.12/site-packages

ENTRYPOINT ["/opt/bin/entrypoint.sh"]

# "--NotebookApp.token=''", "--NotebookApp.password=''"
CMD ["jupyter", "lab", "--no-browser", "--allow-root", "--ip=0.0.0.0", "--port=8888"]
