FROM pytorch/pytorch:2.8.0-cuda12.9-cudnn9-runtime

#### 1. installation
COPY apps /opt/apps
RUN chmod a+x /opt/apps/*.sh

RUN /opt/apps/apt_install.sh \
    tzdata build-essential gosu vim file \
    jq tree dos2unix git openssh-client curl

RUN pip install --no-cache-dir -U -r /opt/apps/pip.txt
# -i https://pypi.tuna.tsinghua.edu.cn/simple

#### 2. config
RUN mkdir -p /root/work /root/.jupyter && \
  cp /opt/apps/jupyter_lab_config.py /root/.jupyter/ && \
  mkdir -p  /home/appuser/work /home/appuser/.jupyter && \
  cp /opt/apps/jupyter_lab_config.py /home/appuser/.jupyter/

RUN userdel -r ubuntu || true

#### 3. define
# default=/workspace
WORKDIR /root/work

EXPOSE 8888

VOLUME ["/root/work", "/home/appuser/work"]

ENV TZ=Asia/Shanghai
#ENV PATH=/root/work/data/pip_packages/bin:/opt/conda/bin:$PATH
#ENV PYTHONPATH=/root/work/data/pip_packages:/opt/conda/lib/python3.11/site-packages

ENTRYPOINT ["/opt/apps/entrypoint.sh"]

#### 4. run
# "--NotebookApp.token=''", "--NotebookApp.password=''"
CMD ["jupyter", "lab", "--no-browser", "--allow-root", "--ip=0.0.0.0", "--port=8888"]
