services:
  codebox:
    image: q.local/codebox:latest
    restart: always # unless-stopped
    container_name: codebox
    hostname: codebox
    cap_add: [NET_ADMIN]
    devices: [/dev/net/tun:/dev/net/tun]
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
      net.ipv6.conf.default.disable_ipv6: "1"
    extra_hosts:
      host.docker.internal: host-gateway
    network_mode: bridge
    #ports: [127.0.0.1:4222:4222, 127.0.0.1:7681:7681]
    user: root:root
    volumes:
    - ./data/config:/home/appuser/.config
    - ./data/cache:/home/appuser/.cache
    - ./data/share:/home/appuser/.local/share
    - ./data/state:/home/appuser/.local/state
    - ./data/apps:/home/appuser/apps
    - ./data/workspace:/home/appuser/workspace

    #- ./configs/:/app/configs
    #- ./logs:/app/logs
    #- ./configs/sshd_config.d:/etc/ssh/sshd_config.d
    #- ./configs/ssh:/home/appuser/.ssh
    working_dir: /home/appuser/workspace
    environment:
      TZ: UTC
      https_proxy: http://127.0.0.1:1080
      http_proxy: http://127.0.0.1:1080
      no_proxy: ""
      HTTPS_PROXY: http://127.0.0.1:1080
      HTTP_PROXY: http://127.0.0.1:1080
      NO_PROXY: ""
      CLAUDE_CODE_NO_FLICKER: "1"
      DISABLE_AUTOUPDATER: "1"
      DISABLE_INSTALLATION_CHECKS: "1"
      DISABLE_LOGIN_COMMAND: "1"
      DISABLE_LOGOUT_COMMAND: "1"
      DISABLE_UPGRADE_COMMAND: "1"
      # ANTHROPIC_BASE_URL: ""
      # ANTHROPIC_API_KEY: ""
      # ANTHROPIC_MODEL: ""
    command: ["sing-box", "run", "-c=/app/configs/sing-box.tun.json"]
    #command: ["supervisord", "-l", "/app/logs/supervisord.log", "-c", "/app/configs/supervisord.conf"]
