FROM q.local/codebox:latest

####
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy="$http_proxy" https_proxy="$https_proxy" no_proxy="$no_proxy"

####
USER root
ADD copy_files/scripts/_install_playwright.sh /opt/scripts/_install_playwright.sh

RUN /opt/scripts/_install_playwright.sh
ENV PLAYWRIGHT_BROWSERS_PATH=/opt/ms-playwright

USER appuser
WORKDIR /home/appuser

WORKDIR /home/appuser/workspace

####
ENV https_proxy="" http_proxy="" no_proxy=""
