FROM q.local/opencode:latest

####
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

####
USER root
RUN apt_install.sh

UEER appuser
WORKDIR /home/appuser

#RUN npm install -g opencode-ai@latest
RUN npm update -g opencode-ai@latest

WORKDIR /home/appuser/workspace

####
ENV https_proxy="" \
    http_proxy="" \
    no_proxy=""
