FROM q.local/pyjs:trixie

####
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

####
USER root

COPY ./copy_files/scripts/. /opt/scripts
RUN bash /opt/scripts/_install_tools.sh
RUN mkdir -p /app/configs /app/logs

####
USER appuser
WORKDIR /home/appuser

ENV CLAUDE_CONFIG_DIR=/home/appuser/.config/claude \
    OTEL_EXPORTER_OTLP_ENDPOINT="" \
    OTEL_METRICS_EXPORTER="" \
    OTEL_LOGS_EXPORTER="" \
    DISABLE_TELEMETRY=1 \
    DISABLE_ERROR_REPORTING=1 \
    DISABLE_FEEDBACK_COMMAND=1 \
    CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY=1 \
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
# CLAUDE_CONFIG_DIR default: ~/.claude.json, ~/.claude/{backups,cache,downloads}

ENV CODEX_HOME=/home/appuser/.local/share/codex

RUN bash /opt/scripts/_install_codebox.sh && \
    rm -rf ~/.cache ~/.npm

RUN mkdir -p ~/.cache

####
ENV https_proxy="" \
    http_proxy="" \
    no_proxy=""

# tyyd, ssh
EXPOSE 7681 4222
USER root

WORKDIR /home/appuser/workspace

ENTRYPOINT []

#CMD ["sing-box", "run", "-c=/app/configs/sing-box.tun.json"]
CMD ["supervisord", "-l", "/app/logs/supervisord.log", "-c", "/app/configs/supervisord.conf"]
