FROM local/node:24-trixie

####
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

ARG build_region

USER root
COPY ./copy_files/bin/. /opt/bin/
RUN apt_install.sh iproute2 netcat-openbsd

####
ENV OPENCODE_SERVER_USERNAME="opencode" \
    OPENCODE_SERVER_PASSWORD="" \
    CODEX_HOME=/home/appuser/xdg/codex
# default: OPENCODE_CONFIG_DIR=~/.config/opencode

USER appuser
WORKDIR /home/appuser

ADD ./copy_files/bash_x .bash_x

RUN if [ "$build_region" == "cn" ]; then \
        npm config set registry https://registry.npmmirror.com; \
        pip3 config set global.index-url 'https://pypi.tuna.tsinghua.edu.cn/simple'; \
        pip3 config set install.trusted-host 'pypi.tuna.tsinghua.edu.cn'; \
    fi

####
RUN npm install -g \
      opencode-ai@latest oh-my-opencode@latest \
      @fission-ai/openspec@latest \
      @openai/codex \
      @google/gemini-cli && \
    rm -rf .npm .cache

# curl -fsSL https://opencode.ai/install | bash
# npx -y oh-my-opencode install
# npm list -g --depth=0

####
ENV https_proxy="" \
    http_proxy="" \
    no_proxy=""

VOLUME /home/appuser/apps

WORKDIR /home/appuser/workspace

# webui
EXPOSE 4096
# auth callback
EXPOSE 1455

# opencode webui
CMD ["opencode", "web", "--cwd=/home/appuser/workspace", "--hostname=0.0.0.0", "--port=4096"]
# --cors http://localhost:4096 --cors https://app.example.com
# Works exclusively on the host network model: --mdns fase --mdns-domain opencode.local

# opencode tui
#CMD ["opencode"]

# sleep
#CMD ["sleep", "infinity"]
