#!/usr/bin/expect
set prompt "#"
set timeout 60

# set password "DontUseThisPassword"
# set username [lindex $argv 0];
# set password [lindex $argv 1];

set fh [open "./configs/mongo.secret" r]
set password [read -nonewline $fh]
close $fh

spawn docker exec -it mongo-mongos-1 mongosh \
  mongodb://root@mongo-mongos-1:27017,mongo-mongos-2:27017,mongo-mongos-3:27017/admin

expect "Enter password:"
send "$password\r"
interact
# expect eof
