download:
	bash k8s_cluster.sh download

check:
	bash k8s_cluster.sh check

create-mini:
	bash k8s_cluster.sh create mini

create-full:
	bash k8s_cluster.sh create full

list:
	bash k8s_cluster.sh list

start:
	bash k8s_cluster.sh start

down:
	bash k8s_cluster.sh down

erase:
	bash k8s_cluster.sh erase
