networks:
  net: { name: milvus, driver: bridge, external: false }

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.6.8
    expose: [2379, 2380]
    networks: [net]
    ports: [127.0.0.1:2379:2379]
    volumes:
    - ./data/etcd:/etcd
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: 1000
      ETCD_QUOTA_BACKEND_BYTES: 4294967296
      ETCD_SNAPSHOT_COUNT: 50000
    command:
    - etcd
    - --data-dir=/etcd
    - --name=milvus-etcd
    - --advertise-client-urls=http://localhost:2379
    - --listen-client-urls=http://0.0.0.0:2379
    - --listen-peer-urls=http://0.0.0.0:2380

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    networks: [net]
    ports: ["9000:9000", "9090:9090"]
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
    - ./data/minio:/minio_data
    command: minio server /minio_data

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.6.12
    depends_on: [etcd, minio]
    networks: [net]
    ports: ["19530:19530", "9091:9091"]
    volumes:
    - ./data/milvus:/var/lib/milvus
    #- ./configs/milvus.yaml:/milvus/configs/milvus.yaml
    #- ./configs/milvus:/milvus/configs
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
    command: ["milvus", "run", "standalone"]
