upstream synapse_upstream {
    server synapse:8008;
    keepalive 32;
}

upstream element_web_upstream {
    server element-web:80;
    keepalive 16;
}

server {
    listen 80;
    listen [::]:80;
    server_name chat.example.com matrix.example.com;

    #location /.well-known/acme-challenge/ {
    #    root /var/www/certbot;
    #}

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name chat.example.com;

    charset        utf-8;
    server_tokens  off;
    #gzip           on;

    ssl_certificate     /etc/letsencrypt/live/chat.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chat.example.com/privkey.pem;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers  on;
    ssl_ciphers          ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;

    access_log /var/log/nginx/chat.example.com.access.log;
    error_log  /var/log/nginx/chat.example.com.error.log warn;

    location / {
        proxy_pass http://element_web_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name matrix.example.com;

    charset        utf-8;
    server_tokens  off;
    #gzip           on;
    client_max_body_size 100M;
    client_body_buffer_size  16k;

    ssl_certificate     /etc/letsencrypt/live/matrix.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/matrix.example.com/privkey.pem;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers  on;
    ssl_ciphers          ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;

    access_log /var/log/nginx/matrix.example.com.access.log;
    error_log  /var/log/nginx/matrix.example.com.error.log warn;

    location ~ ^(/_matrix|/_synapse/client) {
        proxy_pass http://synapse_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
    }

    location / {
        return 404;
    }
}
