FROM alpine:3

ARG BUILD_Region BUILD_Time

ENV TZ=${TZ:-Asia/Shanghai} BUILD_Region=${BUILD_Region} BUILD_Time=${BUILD_Time}

ADD Containerfile /apps/

RUN if [ "$BUILD_Region" = "cn" ]; then \
    echo "==> BUILD_Region: $BUILD_Region"; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade && \
  apk --no-cache add tzdata coreutils vim jq yq bash curl supervisor gcompat openssl
  # nmap openssh logroate openvpn

RUN mkdir -p /apps/configs /apps/logs /apps/data
WORKDIR /apps

# CMD ["/bin/bash"]
CMD [sleep, infinity]
