FROM debian:trixie-slim

# syntax=docker/dockerfile:1.6

#ARG user_uid=1000
#ARG user_gid=1000

ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    TZ=Asia/Shanghai \
    XDG_CONFIG_HOME=/home/appuser/xdg/config \
    XDG_CACHE_HOME=/home/appuser/xdg/cache \
    XDG_DATA_HOME=/home/appuser/xdg/share \
    XDG_STATE_HOME=/home/appuser/xdg/state \
    PATH=/home/appuser/workspace/xdg/bin:/opt/bin:$PATH

# XDG_CONFIG_HOME=~/.config
# XDG_DATA_HOME=~/.local/share
# XDG_STATE_HOME=~/.local/share
# XDG_CACHE_HOME=~/.cache
# XDG_CACHE_HOME=~/.cache
# XDG_RUNTIME_DIR=/run/user/$UID

COPY copy_files/bin /opt/bin

RUN apt_install.sh tzdata ca-certificates locales gosu file zip unzip && \
    update-ca-certificates
# python3 python3-venv python3-pip python3-dev
# supervisor podman

#RUN groupadd -g $user_gid appuser && \
#    useradd -m -s /bin/bash -u $user_uid -g $user_gid appuser
#USER appuser
#WORKDIR /home/appuser
RUN mkdir -p /home/appuser/workspace /home/appuser/xdg

VOLUME /home/appuser/xdg
VOLUME /home/appuser/workspace
WORKDIR /home/appuser/workspace

ENV http_proxy="" \
    https_proxy="" \
    no_proxy=""

ENV APPUSER_UID=1000 \
    APPUSER_GID=1000

ENTRYPOINT ["/opt/bin/entrypoint.sh"]
CMD ["echo", "You are already in the container"]
