FROM python:3.14-slim-trixie

#### 1. passing args
ARG http_proxy
ARG https_proxy
ARG no_proxy

ARG user_uid=1000
ARG user_gid=1000
ARG build_region

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    no_proxy=$no_proxy

LABEL maintainer="d2jvkpn"

#### 2. installation
ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive

RUN apt update -y && \
    apt upgrade -y --no-install-recommends && \
    apt install -y --no-install-recommends tzdata locales ca-certificates gnupg gosu && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*

#### 3. build
RUN groupadd -g $user_gid appuser && \
    useradd -m -s /bin/bash -u $user_uid -g $user_gid appuser

USER appuser
ENV PATH=/home/appuser/.local/bin:$PATH

RUN if [ "$build_region" == "cn" ]; then \
        pip3 config set global.index-url 'https://pypi.tuna.tsinghua.edu.cn/simple'; \
        pip3 config set install.trusted-host 'pypi.tuna.tsinghua.edu.cn'; \
    fi

RUN mkdir -p /home/appuser/app/configs /home/appuser/app/data /home/appuser/app/logs
WORKDIR /home/appuser/app

RUN pip install --no-cache-dir --upgrade pip wheel setuptools uv

#### 4. container
ENV http_proxy="" \
    https_proxy="" \
    no_proxy=""

VOLUME /home/appuser/app/configs
VOLUME /home/appuser/app/data
VOLUME /home/appuser/app/logs
# EXPOSE 8000

ENTRYPOINT []
CMD ["sleep", "infinity"]
