SELECT TABLE_NAME, ENGINE, CREATE_TIME, UPDATE_TIME
  FROM INFORMATION_SCHEMA.TABLES
  WHERE TABLE_SCHEMA = 'dbname';


SELECT 
  MIN(CREATE_TIME) AS estimated_db_creation_time
FROM
  INFORMATION_SCHEMA.TABLES
WHERE
  TABLE_SCHEMA = 'dbname';
