FROM node:22-alpine AS builder

ARG APP_Name
ARG APP_Version
ARG BASE_Path
ARG region

MAINTAINER github.com/d2jvkpn <d2jvkpn@noreply.local>

LABEL app=${APP_Name}
LABEL version=${APP_Version}
LABEL stage=build

#SHELL ["/bin/bash", "-c"]

WORKDIR /opt

RUN echo "==> BASE_Path: ${BASE_Path}"

ADD *.js *.json *.ts index.html ./
COPY public/ ./public
COPY src/ ./src

COPY target/env ./.env
ADD target/build.yaml target/build.json ./target/

RUN if [ "$region" = "cn" ]; then \
    echo "==> region: $region"; \
    npm config set registry https://registry.npmmirror.com; \
  fi

# can't use RUN --mount=type=bind,target=/opt/node_modules,source=./node_modules ...., why?
COPY node_modules ./node_modules

# npm install --registry=https://registry.npmmirror.com &> /dev/null
RUN npm install && \
  npm run build -- --base=${BASE_Path} --outDir=target/dist${BASE_Path}



####
FROM nginx:1-alpine

ARG APP_Name
ARG APP_Version
ARG BASE_Path

MAINTAINER github.com/d2jvkpn <d2jvkpn@noreply.local>
LABEL app=${APP_Name}
LABEL version=${APP_Version}
LABEL stage=running

ENV APP_Name=${APP_Name}
ENV APP_Version=${APP_Version}
ENV TZ=${TZ:-Asia/Shanghai}

WORKDIR /opt

COPY --from=builder /opt/target ./target
RUN mkdir -p logs

RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bk
# sed -i '/worker_processes/s#auto#4#' /etc/nginx/nginx.conf

COPY deploy/default.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
#CMD ["nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
