FROM kylemanna/openvpn:local

RUN mkdir -p /apps/target /apps/logs
ADD deployments/openvpn_logrotate.sh /apps/target/

RUN crontab -l > /etc/crontab.bk && \
  echo "0 0 1 * * bash /apps/target/openvpn_logrotate.sh" > temp.crontab && \
  crontab temp.crontab && \
  rm temp.crontab

RUN apk --no-cache update && \
  apk --no-cache upgrade && \
  apk --no-cache add supervisor coreutils tzdata

RUN cp /etc/supervisord.conf /etc/supervisord.conf.bk
ADD deployments/supervisord.conf /etc/supervisord.conf
ADD deployments/supervisor.ini /etc/supervisor.d/

CMD [supervisord, -l, /apps/logs/supervisord.log, -c, /etc/supervisord.conf]
