#### custom
client-config-dir     /etc/openvpn/ccd
log-append            /home/appuser/logs/openvpn.log
ifconfig-pool-persist /etc/openvpn/ifconfig-pool-persist.txt 3600

#client-connect       /apps/target/vpn_connect.sh
#client-disconnect    /apps/target/vpn_disconnect.sh
# bash: echo $common_name,$trusted_ip,$trusted_port,$ifconfig_pool_remote_ip"
