####
FROM golang:1-alpine AS builder

ARG APP_Name
ARG APP_Version
ARG region

LABEL app=${APP_Name}
LABEL version=${APP_Version}
LABEL stage=build

RUN mkdir -p /apps/taregt
WORKDIR /apps

COPY ./frp.git /apps
COPY ./cache.local ./cache.local
ADD ./cache.local/build.yaml /apps/target/

RUN if [ -d ./cache.local/vendor ]; then \
    echo "==> Found cache.local/vendor"; \
    mv ./cache.local/vendor vendor; \
  fi

RUN if [ "$region" = "cn" ]; then \
    echo "==> region: $region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
    go env -w GOPROXY="https://goproxy.cn,direct"; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade

RUN go build -trimpath -ldflags "-w -s" -tags frpc -o target/frpc ./cmd/frpc
RUN go build -trimpath -ldflags "-w -s" -tags frps -o target/frps ./cmd/frps

####
FROM alpine:3

ARG APP_Name
ARG APP_Version
ARG region

LABEL app=${APP_Name}
LABEL version=${APP_Version}
LABEL stage=running

ENV APP_Name=${APP_Name}
ENV APP_Version=${APP_Version}
ENV TZ=${TZ:-Asia/Shanghai}

RUN if [ "$region" = "cn" ]; then \
    echo "==> region: $region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade && \
  apk --no-cache add tzdata
  # curl

RUN mkdir -p /apps/target
WORKDIR /apps

COPY --from=builder /apps/target/ /apps/target/

VOLUME ["/apps/configs", "/apps/data", "/apps/logs"]
EXPOSE 3050 3051

# CMD [./target/frpc, --config=configs/frp_client.toml]
CMD [./target/frps, --config=configs/frp_server.toml]
